Update index.html with scroll bar
KatharaFramework/Netkit-Lab-Generator pull request #34
Opened 2024-07-10 10:35 UTC by vonvans

Added scroll bar to index.html, since it was missing

2024-09-02 17:42 UTC, lorenzo93 commented
Hi @vonvans,

Apologies for the delayed response.

I noticed that in the "files changed" section, there are quite a few modifications beyond just the scrollbar. Would it be possible to simplify your commit?

Thank you!

2024-09-10 18:20 UTC, nguyenluminhvy approved these changes

2024-09-18 13:25 UTC, lorenzo93 requested changes
Hi @vonvans,

Apologies for the delayed response.

I noticed that in the "files changed" section, there are quite a few modifications beyond just the scrollbar. Would it be possible to simplify your commit?

Thank you!

2024-11-09 12:12 UTC, lorenzo93 commented
As there was no response from the original author, and PR #35 supersedes it, I will close this PR without merging.

2024-11-09 12:12 UTC, closed without merging